# Generated by Django 5.2.6 on 2025-11-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_cancel_reason_reservation_canceled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='canceled_by',
        ),
    ]
