# Generated by Django 5.2.6 on 2025-11-12 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservation_canceled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('ACA', 'Académico'), ('DIF', 'Difusión'), ('DEP', 'Deportivo'), ('CUL', 'Cultural'), ('OTR', 'Otro')], default='ACA', max_length=3)),
                ('sede', models.CharField(blank=True, max_length=80, verbose_name='Sede / Campus')),
                ('expected_attendance', models.PositiveIntegerField(default=0, verbose_name='Asistencia esperada')),
                ('visibility', models.CharField(choices=[('PRIV', 'Privado'), ('INT', 'Interno'), ('PUB', 'Público')], default='INT', max_length=4, verbose_name='Visibilidad')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='Requiere registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas logísticas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PEND', 'Pendiente'), ('APPR', 'Aprobado'), ('PUB', 'Publicado'), ('DONE', 'Finalizado'), ('CANC', 'Cancelado')], default='PEND', max_length=5, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPR', 'Aprobar'), ('REJ', 'Rechazar')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.event')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EventServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('ASEO', 'Aseo'), ('SEG', 'Seguridad'), ('AV', 'Audio/Video'), ('CAT', 'Catering')], max_length=5)),
                ('detail', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PEND', 'Pendiente'), ('DO', 'En curso'), ('DONE', 'Listo')], default='PEND', max_length=5)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('setup', models.CharField(blank=True, max_length=80, verbose_name='Montaje')),
                ('buffer_before_min', models.PositiveIntegerField(default=0)),
                ('buffer_after_min', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.event')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.space')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
    ]
