# Generated by Django 5.2.6 on 2025-12-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_eventapproval_eventservicerequest_eventspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attendees_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
